/* License Declaration
MIT License

Copyright (c) 2016 James Hilton

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

*/
var fs = require("fs");

// load UKACD17
class SpellChecker {
	constructor() {
		this.finish = false;
		fs.readFile('lib/UKACD17/UKACD17.TXT','ascii',(error,contents) => {
			if(error) throw error;
			this.ukacd17 = contents;
			this.tmp = contents.split("\r\n");
			this.wArray = {
					  0: "",	// 0 - single letter words
					 AA: "", // AA letter words
					 AB: "", // AB letter words
					 AC: "", // AC letter words
					 AD: "", // AD letter words
					 AE: "", // AE letter words
					 AF: "", // AF letter words
					 AG: "", // AG letter words
					 AH: "", // AH letter words
					 AI: "", // AI letter words
					 AJ: "", // AJ letter words
					 AK: "", // AK letter words
					 AL: "", // AL letter words
					 AM: "", // AM letter words
					 AN: "", // AN letter words
					 AO: "", // AO letter words
					 AP: "", // AP letter words
					 AQ: "", // AQ letter words
					 AR: "", // AR letter words
					 AS: "", // AS letter words
					 AT: "", // AT letter words
					 AU: "", // AU letter words
					 AV: "", // AV letter words
					 AW: "", // AW letter words
					 AX: "", // AX letter words
					 AY: "", // AY letter words
					 AZ: "", // AZ letter words
					 Aa: "", // Aa letter words
					 Ab: "", // Ab letter words
					 Ac: "", // Ac letter words
					 Ad: "", // Ad letter words
					 Ae: "", // Ae letter words
					 Af: "", // Af letter words
					 Ag: "", // Ag letter words
					 Ah: "", // Ah letter words
					 Ai: "", // Ai letter words
					 Aj: "", // Aj letter words
					 Ak: "", // Ak letter words
					 Al: "", // Al letter words
					 Am: "", // Am letter words
					 An: "", // An letter words
					 Ao: "", // Ao letter words
					 Ap: "", // Ap letter words
					 Aq: "", // Aq letter words
					 Ar: "", // Ar letter words
					 As: "", // As letter words
					 At: "", // At letter words
					 Au: "", // Au letter words
					 Av: "", // Av letter words
					 Aw: "", // Aw letter words
					 Ax: "", // Ax letter words
					 Ay: "", // Ay letter words
					 Az: "", // Az letter words
					 BA: "", // BA letter words
					 BB: "", // BB letter words
					 BC: "", // BC letter words
					 BD: "", // BD letter words
					 BE: "", // BE letter words
					 BF: "", // BF letter words
					 BG: "", // BG letter words
					 BH: "", // BH letter words
					 BI: "", // BI letter words
					 BJ: "", // BJ letter words
					 BK: "", // BK letter words
					 BL: "", // BL letter words
					 BM: "", // BM letter words
					 BN: "", // BN letter words
					 BO: "", // BO letter words
					 BP: "", // BP letter words
					 BQ: "", // BQ letter words
					 BR: "", // BR letter words
					 BS: "", // BS letter words
					 BT: "", // BT letter words
					 BU: "", // BU letter words
					 BV: "", // BV letter words
					 BW: "", // BW letter words
					 BX: "", // BX letter words
					 BY: "", // BY letter words
					 BZ: "", // BZ letter words
					 Ba: "", // Ba letter words
					 Bb: "", // Bb letter words
					 Bc: "", // Bc letter words
					 Bd: "", // Bd letter words
					 Be: "", // Be letter words
					 Bf: "", // Bf letter words
					 Bg: "", // Bg letter words
					 Bh: "", // Bh letter words
					 Bi: "", // Bi letter words
					 Bj: "", // Bj letter words
					 Bk: "", // Bk letter words
					 Bl: "", // Bl letter words
					 Bm: "", // Bm letter words
					 Bn: "", // Bn letter words
					 Bo: "", // Bo letter words
					 Bp: "", // Bp letter words
					 Bq: "", // Bq letter words
					 Br: "", // Br letter words
					 Bs: "", // Bs letter words
					 Bt: "", // Bt letter words
					 Bu: "", // Bu letter words
					 Bv: "", // Bv letter words
					 Bw: "", // Bw letter words
					 Bx: "", // Bx letter words
					 By: "", // By letter words
					 Bz: "", // Bz letter words
					 CA: "", // CA letter words
					 CB: "", // CB letter words
					 CC: "", // CC letter words
					 CD: "", // CD letter words
					 CE: "", // CE letter words
					 CF: "", // CF letter words
					 CG: "", // CG letter words
					 CH: "", // CH letter words
					 CI: "", // CI letter words
					 CJ: "", // CJ letter words
					 CK: "", // CK letter words
					 CL: "", // CL letter words
					 CM: "", // CM letter words
					 CN: "", // CN letter words
					 CO: "", // CO letter words
					 CP: "", // CP letter words
					 CQ: "", // CQ letter words
					 CR: "", // CR letter words
					 CS: "", // CS letter words
					 CT: "", // CT letter words
					 CU: "", // CU letter words
					 CV: "", // CV letter words
					 CW: "", // CW letter words
					 CX: "", // CX letter words
					 CY: "", // CY letter words
					 CZ: "", // CZ letter words
					 Ca: "", // Ca letter words
					 Cb: "", // Cb letter words
					 Cc: "", // Cc letter words
					 Cd: "", // Cd letter words
					 Ce: "", // Ce letter words
					 Cf: "", // Cf letter words
					 Cg: "", // Cg letter words
					 Ch: "", // Ch letter words
					 Ci: "", // Ci letter words
					 Cj: "", // Cj letter words
					 Ck: "", // Ck letter words
					 Cl: "", // Cl letter words
					 Cm: "", // Cm letter words
					 Cn: "", // Cn letter words
					 Co: "", // Co letter words
					 Cp: "", // Cp letter words
					 Cq: "", // Cq letter words
					 Cr: "", // Cr letter words
					 Cs: "", // Cs letter words
					 Ct: "", // Ct letter words
					 Cu: "", // Cu letter words
					 Cv: "", // Cv letter words
					 Cw: "", // Cw letter words
					 Cx: "", // Cx letter words
					 Cy: "", // Cy letter words
					 Cz: "", // Cz letter words
					 DA: "", // DA letter words
					 DB: "", // DB letter words
					 DC: "", // DC letter words
					 DD: "", // DD letter words
					 DE: "", // DE letter words
					 DF: "", // DF letter words
					 DG: "", // DG letter words
					 DH: "", // DH letter words
					 DI: "", // DI letter words
					 DJ: "", // DJ letter words
					 DK: "", // DK letter words
					 DL: "", // DL letter words
					 DM: "", // DM letter words
					 DN: "", // DN letter words
					 DO: "", // DO letter words
					 DP: "", // DP letter words
					 DQ: "", // DQ letter words
					 DR: "", // DR letter words
					 DS: "", // DS letter words
					 DT: "", // DT letter words
					 DU: "", // DU letter words
					 DV: "", // DV letter words
					 DW: "", // DW letter words
					 DX: "", // DX letter words
					 DY: "", // DY letter words
					 DZ: "", // DZ letter words
					 Da: "", // Da letter words
					 Db: "", // Db letter words
					 Dc: "", // Dc letter words
					 Dd: "", // Dd letter words
					 De: "", // De letter words
					 Df: "", // Df letter words
					 Dg: "", // Dg letter words
					 Dh: "", // Dh letter words
					 Di: "", // Di letter words
					 Dj: "", // Dj letter words
					 Dk: "", // Dk letter words
					 Dl: "", // Dl letter words
					 Dm: "", // Dm letter words
					 Dn: "", // Dn letter words
					 Do: "", // Do letter words
					 Dp: "", // Dp letter words
					 Dq: "", // Dq letter words
					 Dr: "", // Dr letter words
					 Ds: "", // Ds letter words
					 Dt: "", // Dt letter words
					 Du: "", // Du letter words
					 Dv: "", // Dv letter words
					 Dw: "", // Dw letter words
					 Dx: "", // Dx letter words
					 Dy: "", // Dy letter words
					 Dz: "", // Dz letter words
					 EA: "", // EA letter words
					 EB: "", // EB letter words
					 EC: "", // EC letter words
					 ED: "", // ED letter words
					 EE: "", // EE letter words
					 EF: "", // EF letter words
					 EG: "", // EG letter words
					 EH: "", // EH letter words
					 EI: "", // EI letter words
					 EJ: "", // EJ letter words
					 EK: "", // EK letter words
					 EL: "", // EL letter words
					 EM: "", // EM letter words
					 EN: "", // EN letter words
					 EO: "", // EO letter words
					 EP: "", // EP letter words
					 EQ: "", // EQ letter words
					 ER: "", // ER letter words
					 ES: "", // ES letter words
					 ET: "", // ET letter words
					 EU: "", // EU letter words
					 EV: "", // EV letter words
					 EW: "", // EW letter words
					 EX: "", // EX letter words
					 EY: "", // EY letter words
					 EZ: "", // EZ letter words
					 Ea: "", // Ea letter words
					 Eb: "", // Eb letter words
					 Ec: "", // Ec letter words
					 Ed: "", // Ed letter words
					 Ee: "", // Ee letter words
					 Ef: "", // Ef letter words
					 Eg: "", // Eg letter words
					 Eh: "", // Eh letter words
					 Ei: "", // Ei letter words
					 Ej: "", // Ej letter words
					 Ek: "", // Ek letter words
					 El: "", // El letter words
					 Em: "", // Em letter words
					 En: "", // En letter words
					 Eo: "", // Eo letter words
					 Ep: "", // Ep letter words
					 Eq: "", // Eq letter words
					 Er: "", // Er letter words
					 Es: "", // Es letter words
					 Et: "", // Et letter words
					 Eu: "", // Eu letter words
					 Ev: "", // Ev letter words
					 Ew: "", // Ew letter words
					 Ex: "", // Ex letter words
					 Ey: "", // Ey letter words
					 Ez: "", // Ez letter words
					 FA: "", // FA letter words
					 FB: "", // FB letter words
					 FC: "", // FC letter words
					 FD: "", // FD letter words
					 FE: "", // FE letter words
					 FF: "", // FF letter words
					 FG: "", // FG letter words
					 FH: "", // FH letter words
					 FI: "", // FI letter words
					 FJ: "", // FJ letter words
					 FK: "", // FK letter words
					 FL: "", // FL letter words
					 FM: "", // FM letter words
					 FN: "", // FN letter words
					 FO: "", // FO letter words
					 FP: "", // FP letter words
					 FQ: "", // FQ letter words
					 FR: "", // FR letter words
					 FS: "", // FS letter words
					 FT: "", // FT letter words
					 FU: "", // FU letter words
					 FV: "", // FV letter words
					 FW: "", // FW letter words
					 FX: "", // FX letter words
					 FY: "", // FY letter words
					 FZ: "", // FZ letter words
					 Fa: "", // Fa letter words
					 Fb: "", // Fb letter words
					 Fc: "", // Fc letter words
					 Fd: "", // Fd letter words
					 Fe: "", // Fe letter words
					 Ff: "", // Ff letter words
					 Fg: "", // Fg letter words
					 Fh: "", // Fh letter words
					 Fi: "", // Fi letter words
					 Fj: "", // Fj letter words
					 Fk: "", // Fk letter words
					 Fl: "", // Fl letter words
					 Fm: "", // Fm letter words
					 Fn: "", // Fn letter words
					 Fo: "", // Fo letter words
					 Fp: "", // Fp letter words
					 Fq: "", // Fq letter words
					 Fr: "", // Fr letter words
					 Fs: "", // Fs letter words
					 Ft: "", // Ft letter words
					 Fu: "", // Fu letter words
					 Fv: "", // Fv letter words
					 Fw: "", // Fw letter words
					 Fx: "", // Fx letter words
					 Fy: "", // Fy letter words
					 Fz: "", // Fz letter words
					 GA: "", // GA letter words
					 GB: "", // GB letter words
					 GC: "", // GC letter words
					 GD: "", // GD letter words
					 GE: "", // GE letter words
					 GF: "", // GF letter words
					 GG: "", // GG letter words
					 GH: "", // GH letter words
					 GI: "", // GI letter words
					 GJ: "", // GJ letter words
					 GK: "", // GK letter words
					 GL: "", // GL letter words
					 GM: "", // GM letter words
					 GN: "", // GN letter words
					 GO: "", // GO letter words
					 GP: "", // GP letter words
					 GQ: "", // GQ letter words
					 GR: "", // GR letter words
					 GS: "", // GS letter words
					 GT: "", // GT letter words
					 GU: "", // GU letter words
					 GV: "", // GV letter words
					 GW: "", // GW letter words
					 GX: "", // GX letter words
					 GY: "", // GY letter words
					 GZ: "", // GZ letter words
					 Ga: "", // Ga letter words
					 Gb: "", // Gb letter words
					 Gc: "", // Gc letter words
					 Gd: "", // Gd letter words
					 Ge: "", // Ge letter words
					 Gf: "", // Gf letter words
					 Gg: "", // Gg letter words
					 Gh: "", // Gh letter words
					 Gi: "", // Gi letter words
					 Gj: "", // Gj letter words
					 Gk: "", // Gk letter words
					 Gl: "", // Gl letter words
					 Gm: "", // Gm letter words
					 Gn: "", // Gn letter words
					 Go: "", // Go letter words
					 Gp: "", // Gp letter words
					 Gq: "", // Gq letter words
					 Gr: "", // Gr letter words
					 Gs: "", // Gs letter words
					 Gt: "", // Gt letter words
					 Gu: "", // Gu letter words
					 Gv: "", // Gv letter words
					 Gw: "", // Gw letter words
					 Gx: "", // Gx letter words
					 Gy: "", // Gy letter words
					 Gz: "", // Gz letter words
					 HA: "", // HA letter words
					 HB: "", // HB letter words
					 HC: "", // HC letter words
					 HD: "", // HD letter words
					 HE: "", // HE letter words
					 HF: "", // HF letter words
					 HG: "", // HG letter words
					 HH: "", // HH letter words
					 HI: "", // HI letter words
					 HJ: "", // HJ letter words
					 HK: "", // HK letter words
					 HL: "", // HL letter words
					 HM: "", // HM letter words
					 HN: "", // HN letter words
					 HO: "", // HO letter words
					 HP: "", // HP letter words
					 HQ: "", // HQ letter words
					 HR: "", // HR letter words
					 HS: "", // HS letter words
					 HT: "", // HT letter words
					 HU: "", // HU letter words
					 HV: "", // HV letter words
					 HW: "", // HW letter words
					 HX: "", // HX letter words
					 HY: "", // HY letter words
					 HZ: "", // HZ letter words
					 Ha: "", // Ha letter words
					 Hb: "", // Hb letter words
					 Hc: "", // Hc letter words
					 Hd: "", // Hd letter words
					 He: "", // He letter words
					 Hf: "", // Hf letter words
					 Hg: "", // Hg letter words
					 Hh: "", // Hh letter words
					 Hi: "", // Hi letter words
					 Hj: "", // Hj letter words
					 Hk: "", // Hk letter words
					 Hl: "", // Hl letter words
					 Hm: "", // Hm letter words
					 Hn: "", // Hn letter words
					 Ho: "", // Ho letter words
					 Hp: "", // Hp letter words
					 Hq: "", // Hq letter words
					 Hr: "", // Hr letter words
					 Hs: "", // Hs letter words
					 Ht: "", // Ht letter words
					 Hu: "", // Hu letter words
					 Hv: "", // Hv letter words
					 Hw: "", // Hw letter words
					 Hx: "", // Hx letter words
					 Hy: "", // Hy letter words
					 Hz: "", // Hz letter words
					 IA: "", // IA letter words
					 IB: "", // IB letter words
					 IC: "", // IC letter words
					 ID: "", // ID letter words
					 IE: "", // IE letter words
					 IF: "", // IF letter words
					 IG: "", // IG letter words
					 IH: "", // IH letter words
					 II: "", // II letter words
					 IJ: "", // IJ letter words
					 IK: "", // IK letter words
					 IL: "", // IL letter words
					 IM: "", // IM letter words
					 IN: "", // IN letter words
					 IO: "", // IO letter words
					 IP: "", // IP letter words
					 IQ: "", // IQ letter words
					 IR: "", // IR letter words
					 IS: "", // IS letter words
					 IT: "", // IT letter words
					 IU: "", // IU letter words
					 IV: "", // IV letter words
					 IW: "", // IW letter words
					 IX: "", // IX letter words
					 IY: "", // IY letter words
					 IZ: "", // IZ letter words
					 Ia: "", // Ia letter words
					 Ib: "", // Ib letter words
					 Ic: "", // Ic letter words
					 Id: "", // Id letter words
					 Ie: "", // Ie letter words
					 If: "", // If letter words
					 Ig: "", // Ig letter words
					 Ih: "", // Ih letter words
					 Ii: "", // Ii letter words
					 Ij: "", // Ij letter words
					 Ik: "", // Ik letter words
					 Il: "", // Il letter words
					 Im: "", // Im letter words
					 In: "", // In letter words
					 Io: "", // Io letter words
					 Ip: "", // Ip letter words
					 Iq: "", // Iq letter words
					 Ir: "", // Ir letter words
					 Is: "", // Is letter words
					 It: "", // It letter words
					 Iu: "", // Iu letter words
					 Iv: "", // Iv letter words
					 Iw: "", // Iw letter words
					 Ix: "", // Ix letter words
					 Iy: "", // Iy letter words
					 Iz: "", // Iz letter words
					 JA: "", // JA letter words
					 JB: "", // JB letter words
					 JC: "", // JC letter words
					 JD: "", // JD letter words
					 JE: "", // JE letter words
					 JF: "", // JF letter words
					 JG: "", // JG letter words
					 JH: "", // JH letter words
					 JI: "", // JI letter words
					 JJ: "", // JJ letter words
					 JK: "", // JK letter words
					 JL: "", // JL letter words
					 JM: "", // JM letter words
					 JN: "", // JN letter words
					 JO: "", // JO letter words
					 JP: "", // JP letter words
					 JQ: "", // JQ letter words
					 JR: "", // JR letter words
					 JS: "", // JS letter words
					 JT: "", // JT letter words
					 JU: "", // JU letter words
					 JV: "", // JV letter words
					 JW: "", // JW letter words
					 JX: "", // JX letter words
					 JY: "", // JY letter words
					 JZ: "", // JZ letter words
					 Ja: "", // Ja letter words
					 Jb: "", // Jb letter words
					 Jc: "", // Jc letter words
					 Jd: "", // Jd letter words
					 Je: "", // Je letter words
					 Jf: "", // Jf letter words
					 Jg: "", // Jg letter words
					 Jh: "", // Jh letter words
					 Ji: "", // Ji letter words
					 Jj: "", // Jj letter words
					 Jk: "", // Jk letter words
					 Jl: "", // Jl letter words
					 Jm: "", // Jm letter words
					 Jn: "", // Jn letter words
					 Jo: "", // Jo letter words
					 Jp: "", // Jp letter words
					 Jq: "", // Jq letter words
					 Jr: "", // Jr letter words
					 Js: "", // Js letter words
					 Jt: "", // Jt letter words
					 Ju: "", // Ju letter words
					 Jv: "", // Jv letter words
					 Jw: "", // Jw letter words
					 Jx: "", // Jx letter words
					 Jy: "", // Jy letter words
					 Jz: "", // Jz letter words
					 KA: "", // KA letter words
					 KB: "", // KB letter words
					 KC: "", // KC letter words
					 KD: "", // KD letter words
					 KE: "", // KE letter words
					 KF: "", // KF letter words
					 KG: "", // KG letter words
					 KH: "", // KH letter words
					 KI: "", // KI letter words
					 KJ: "", // KJ letter words
					 KK: "", // KK letter words
					 KL: "", // KL letter words
					 KM: "", // KM letter words
					 KN: "", // KN letter words
					 KO: "", // KO letter words
					 KP: "", // KP letter words
					 KQ: "", // KQ letter words
					 KR: "", // KR letter words
					 KS: "", // KS letter words
					 KT: "", // KT letter words
					 KU: "", // KU letter words
					 KV: "", // KV letter words
					 KW: "", // KW letter words
					 KX: "", // KX letter words
					 KY: "", // KY letter words
					 KZ: "", // KZ letter words
					 Ka: "", // Ka letter words
					 Kb: "", // Kb letter words
					 Kc: "", // Kc letter words
					 Kd: "", // Kd letter words
					 Ke: "", // Ke letter words
					 Kf: "", // Kf letter words
					 Kg: "", // Kg letter words
					 Kh: "", // Kh letter words
					 Ki: "", // Ki letter words
					 Kj: "", // Kj letter words
					 Kk: "", // Kk letter words
					 Kl: "", // Kl letter words
					 Km: "", // Km letter words
					 Kn: "", // Kn letter words
					 Ko: "", // Ko letter words
					 Kp: "", // Kp letter words
					 Kq: "", // Kq letter words
					 Kr: "", // Kr letter words
					 Ks: "", // Ks letter words
					 Kt: "", // Kt letter words
					 Ku: "", // Ku letter words
					 Kv: "", // Kv letter words
					 Kw: "", // Kw letter words
					 Kx: "", // Kx letter words
					 Ky: "", // Ky letter words
					 Kz: "", // Kz letter words
					 LA: "", // LA letter words
					 LB: "", // LB letter words
					 LC: "", // LC letter words
					 LD: "", // LD letter words
					 LE: "", // LE letter words
					 LF: "", // LF letter words
					 LG: "", // LG letter words
					 LH: "", // LH letter words
					 LI: "", // LI letter words
					 LJ: "", // LJ letter words
					 LK: "", // LK letter words
					 LL: "", // LL letter words
					 LM: "", // LM letter words
					 LN: "", // LN letter words
					 LO: "", // LO letter words
					 LP: "", // LP letter words
					 LQ: "", // LQ letter words
					 LR: "", // LR letter words
					 LS: "", // LS letter words
					 LT: "", // LT letter words
					 LU: "", // LU letter words
					 LV: "", // LV letter words
					 LW: "", // LW letter words
					 LX: "", // LX letter words
					 LY: "", // LY letter words
					 LZ: "", // LZ letter words
					 La: "", // La letter words
					 Lb: "", // Lb letter words
					 Lc: "", // Lc letter words
					 Ld: "", // Ld letter words
					 Le: "", // Le letter words
					 Lf: "", // Lf letter words
					 Lg: "", // Lg letter words
					 Lh: "", // Lh letter words
					 Li: "", // Li letter words
					 Lj: "", // Lj letter words
					 Lk: "", // Lk letter words
					 Ll: "", // Ll letter words
					 Lm: "", // Lm letter words
					 Ln: "", // Ln letter words
					 Lo: "", // Lo letter words
					 Lp: "", // Lp letter words
					 Lq: "", // Lq letter words
					 Lr: "", // Lr letter words
					 Ls: "", // Ls letter words
					 Lt: "", // Lt letter words
					 Lu: "", // Lu letter words
					 Lv: "", // Lv letter words
					 Lw: "", // Lw letter words
					 Lx: "", // Lx letter words
					 Ly: "", // Ly letter words
					 Lz: "", // Lz letter words
					 MA: "", // MA letter words
					 MB: "", // MB letter words
					 MC: "", // MC letter words
					 MD: "", // MD letter words
					 ME: "", // ME letter words
					 MF: "", // MF letter words
					 MG: "", // MG letter words
					 MH: "", // MH letter words
					 MI: "", // MI letter words
					 MJ: "", // MJ letter words
					 MK: "", // MK letter words
					 ML: "", // ML letter words
					 MM: "", // MM letter words
					 MN: "", // MN letter words
					 MO: "", // MO letter words
					 MP: "", // MP letter words
					 MQ: "", // MQ letter words
					 MR: "", // MR letter words
					 MS: "", // MS letter words
					 MT: "", // MT letter words
					 MU: "", // MU letter words
					 MV: "", // MV letter words
					 MW: "", // MW letter words
					 MX: "", // MX letter words
					 MY: "", // MY letter words
					 MZ: "", // MZ letter words
					 Ma: "", // Ma letter words
					 Mb: "", // Mb letter words
					 Mc: "", // Mc letter words
					 Md: "", // Md letter words
					 Me: "", // Me letter words
					 Mf: "", // Mf letter words
					 Mg: "", // Mg letter words
					 Mh: "", // Mh letter words
					 Mi: "", // Mi letter words
					 Mj: "", // Mj letter words
					 Mk: "", // Mk letter words
					 Ml: "", // Ml letter words
					 Mm: "", // Mm letter words
					 Mn: "", // Mn letter words
					 Mo: "", // Mo letter words
					 Mp: "", // Mp letter words
					 Mq: "", // Mq letter words
					 Mr: "", // Mr letter words
					 Ms: "", // Ms letter words
					 Mt: "", // Mt letter words
					 Mu: "", // Mu letter words
					 Mv: "", // Mv letter words
					 Mw: "", // Mw letter words
					 Mx: "", // Mx letter words
					 My: "", // My letter words
					 Mz: "", // Mz letter words
					 NA: "", // NA letter words
					 NB: "", // NB letter words
					 NC: "", // NC letter words
					 ND: "", // ND letter words
					 NE: "", // NE letter words
					 NF: "", // NF letter words
					 NG: "", // NG letter words
					 NH: "", // NH letter words
					 NI: "", // NI letter words
					 NJ: "", // NJ letter words
					 NK: "", // NK letter words
					 NL: "", // NL letter words
					 NM: "", // NM letter words
					 NN: "", // NN letter words
					 NO: "", // NO letter words
					 NP: "", // NP letter words
					 NQ: "", // NQ letter words
					 NR: "", // NR letter words
					 NS: "", // NS letter words
					 NT: "", // NT letter words
					 NU: "", // NU letter words
					 NV: "", // NV letter words
					 NW: "", // NW letter words
					 NX: "", // NX letter words
					 NY: "", // NY letter words
					 NZ: "", // NZ letter words
					 Na: "", // Na letter words
					 Nb: "", // Nb letter words
					 Nc: "", // Nc letter words
					 Nd: "", // Nd letter words
					 Ne: "", // Ne letter words
					 Nf: "", // Nf letter words
					 Ng: "", // Ng letter words
					 Nh: "", // Nh letter words
					 Ni: "", // Ni letter words
					 Nj: "", // Nj letter words
					 Nk: "", // Nk letter words
					 Nl: "", // Nl letter words
					 Nm: "", // Nm letter words
					 Nn: "", // Nn letter words
					 No: "", // No letter words
					 Np: "", // Np letter words
					 Nq: "", // Nq letter words
					 Nr: "", // Nr letter words
					 Ns: "", // Ns letter words
					 Nt: "", // Nt letter words
					 Nu: "", // Nu letter words
					 Nv: "", // Nv letter words
					 Nw: "", // Nw letter words
					 Nx: "", // Nx letter words
					 Ny: "", // Ny letter words
					 Nz: "", // Nz letter words
					 OA: "", // OA letter words
					 OB: "", // OB letter words
					 OC: "", // OC letter words
					 OD: "", // OD letter words
					 OE: "", // OE letter words
					 OF: "", // OF letter words
					 OG: "", // OG letter words
					 OH: "", // OH letter words
					 OI: "", // OI letter words
					 OJ: "", // OJ letter words
					 OK: "", // OK letter words
					 OL: "", // OL letter words
					 OM: "", // OM letter words
					 ON: "", // ON letter words
					 OO: "", // OO letter words
					 OP: "", // OP letter words
					 OQ: "", // OQ letter words
					 OR: "", // OR letter words
					 OS: "", // OS letter words
					 OT: "", // OT letter words
					 OU: "", // OU letter words
					 OV: "", // OV letter words
					 OW: "", // OW letter words
					 OX: "", // OX letter words
					 OY: "", // OY letter words
					 OZ: "", // OZ letter words
					 Oa: "", // Oa letter words
					 Ob: "", // Ob letter words
					 Oc: "", // Oc letter words
					 Od: "", // Od letter words
					 Oe: "", // Oe letter words
					 Of: "", // Of letter words
					 Og: "", // Og letter words
					 Oh: "", // Oh letter words
					 Oi: "", // Oi letter words
					 Oj: "", // Oj letter words
					 Ok: "", // Ok letter words
					 Ol: "", // Ol letter words
					 Om: "", // Om letter words
					 On: "", // On letter words
					 Oo: "", // Oo letter words
					 Op: "", // Op letter words
					 Oq: "", // Oq letter words
					 Or: "", // Or letter words
					 Os: "", // Os letter words
					 Ot: "", // Ot letter words
					 Ou: "", // Ou letter words
					 Ov: "", // Ov letter words
					 Ow: "", // Ow letter words
					 Ox: "", // Ox letter words
					 Oy: "", // Oy letter words
					 Oz: "", // Oz letter words
					 PA: "", // PA letter words
					 PB: "", // PB letter words
					 PC: "", // PC letter words
					 PD: "", // PD letter words
					 PE: "", // PE letter words
					 PF: "", // PF letter words
					 PG: "", // PG letter words
					 PH: "", // PH letter words
					 PI: "", // PI letter words
					 PJ: "", // PJ letter words
					 PK: "", // PK letter words
					 PL: "", // PL letter words
					 PM: "", // PM letter words
					 PN: "", // PN letter words
					 PO: "", // PO letter words
					 PP: "", // PP letter words
					 PQ: "", // PQ letter words
					 PR: "", // PR letter words
					 PS: "", // PS letter words
					 PT: "", // PT letter words
					 PU: "", // PU letter words
					 PV: "", // PV letter words
					 PW: "", // PW letter words
					 PX: "", // PX letter words
					 PY: "", // PY letter words
					 PZ: "", // PZ letter words
					 Pa: "", // Pa letter words
					 Pb: "", // Pb letter words
					 Pc: "", // Pc letter words
					 Pd: "", // Pd letter words
					 Pe: "", // Pe letter words
					 Pf: "", // Pf letter words
					 Pg: "", // Pg letter words
					 Ph: "", // Ph letter words
					 Pi: "", // Pi letter words
					 Pj: "", // Pj letter words
					 Pk: "", // Pk letter words
					 Pl: "", // Pl letter words
					 Pm: "", // Pm letter words
					 Pn: "", // Pn letter words
					 Po: "", // Po letter words
					 Pp: "", // Pp letter words
					 Pq: "", // Pq letter words
					 Pr: "", // Pr letter words
					 Ps: "", // Ps letter words
					 Pt: "", // Pt letter words
					 Pu: "", // Pu letter words
					 Pv: "", // Pv letter words
					 Pw: "", // Pw letter words
					 Px: "", // Px letter words
					 Py: "", // Py letter words
					 Pz: "", // Pz letter words
					 QA: "", // QA letter words
					 QB: "", // QB letter words
					 QC: "", // QC letter words
					 QD: "", // QD letter words
					 QE: "", // QE letter words
					 QF: "", // QF letter words
					 QG: "", // QG letter words
					 QH: "", // QH letter words
					 QI: "", // QI letter words
					 QJ: "", // QJ letter words
					 QK: "", // QK letter words
					 QL: "", // QL letter words
					 QM: "", // QM letter words
					 QN: "", // QN letter words
					 QO: "", // QO letter words
					 QP: "", // QP letter words
					 QQ: "", // QQ letter words
					 QR: "", // QR letter words
					 QS: "", // QS letter words
					 QT: "", // QT letter words
					 QU: "", // QU letter words
					 QV: "", // QV letter words
					 QW: "", // QW letter words
					 QX: "", // QX letter words
					 QY: "", // QY letter words
					 QZ: "", // QZ letter words
					 Qa: "", // Qa letter words
					 Qb: "", // Qb letter words
					 Qc: "", // Qc letter words
					 Qd: "", // Qd letter words
					 Qe: "", // Qe letter words
					 Qf: "", // Qf letter words
					 Qg: "", // Qg letter words
					 Qh: "", // Qh letter words
					 Qi: "", // Qi letter words
					 Qj: "", // Qj letter words
					 Qk: "", // Qk letter words
					 Ql: "", // Ql letter words
					 Qm: "", // Qm letter words
					 Qn: "", // Qn letter words
					 Qo: "", // Qo letter words
					 Qp: "", // Qp letter words
					 Qq: "", // Qq letter words
					 Qr: "", // Qr letter words
					 Qs: "", // Qs letter words
					 Qt: "", // Qt letter words
					 Qu: "", // Qu letter words
					 Qv: "", // Qv letter words
					 Qw: "", // Qw letter words
					 Qx: "", // Qx letter words
					 Qy: "", // Qy letter words
					 Qz: "", // Qz letter words
					 RA: "", // RA letter words
					 RB: "", // RB letter words
					 RC: "", // RC letter words
					 RD: "", // RD letter words
					 RE: "", // RE letter words
					 RF: "", // RF letter words
					 RG: "", // RG letter words
					 RH: "", // RH letter words
					 RI: "", // RI letter words
					 RJ: "", // RJ letter words
					 RK: "", // RK letter words
					 RL: "", // RL letter words
					 RM: "", // RM letter words
					 RN: "", // RN letter words
					 RO: "", // RO letter words
					 RP: "", // RP letter words
					 RQ: "", // RQ letter words
					 RR: "", // RR letter words
					 RS: "", // RS letter words
					 RT: "", // RT letter words
					 RU: "", // RU letter words
					 RV: "", // RV letter words
					 RW: "", // RW letter words
					 RX: "", // RX letter words
					 RY: "", // RY letter words
					 RZ: "", // RZ letter words
					 Ra: "", // Ra letter words
					 Rb: "", // Rb letter words
					 Rc: "", // Rc letter words
					 Rd: "", // Rd letter words
					 Re: "", // Re letter words
					 Rf: "", // Rf letter words
					 Rg: "", // Rg letter words
					 Rh: "", // Rh letter words
					 Ri: "", // Ri letter words
					 Rj: "", // Rj letter words
					 Rk: "", // Rk letter words
					 Rl: "", // Rl letter words
					 Rm: "", // Rm letter words
					 Rn: "", // Rn letter words
					 Ro: "", // Ro letter words
					 Rp: "", // Rp letter words
					 Rq: "", // Rq letter words
					 Rr: "", // Rr letter words
					 Rs: "", // Rs letter words
					 Rt: "", // Rt letter words
					 Ru: "", // Ru letter words
					 Rv: "", // Rv letter words
					 Rw: "", // Rw letter words
					 Rx: "", // Rx letter words
					 Ry: "", // Ry letter words
					 Rz: "", // Rz letter words
					 SA: "", // SA letter words
					 SB: "", // SB letter words
					 SC: "", // SC letter words
					 SD: "", // SD letter words
					 SE: "", // SE letter words
					 SF: "", // SF letter words
					 SG: "", // SG letter words
					 SH: "", // SH letter words
					 SI: "", // SI letter words
					 SJ: "", // SJ letter words
					 SK: "", // SK letter words
					 SL: "", // SL letter words
					 SM: "", // SM letter words
					 SN: "", // SN letter words
					 SO: "", // SO letter words
					 SP: "", // SP letter words
					 SQ: "", // SQ letter words
					 SR: "", // SR letter words
					 SS: "", // SS letter words
					 ST: "", // ST letter words
					 SU: "", // SU letter words
					 SV: "", // SV letter words
					 SW: "", // SW letter words
					 SX: "", // SX letter words
					 SY: "", // SY letter words
					 SZ: "", // SZ letter words
					 Sa: "", // Sa letter words
					 Sb: "", // Sb letter words
					 Sc: "", // Sc letter words
					 Sd: "", // Sd letter words
					 Se: "", // Se letter words
					 Sf: "", // Sf letter words
					 Sg: "", // Sg letter words
					 Sh: "", // Sh letter words
					 Si: "", // Si letter words
					 Sj: "", // Sj letter words
					 Sk: "", // Sk letter words
					 Sl: "", // Sl letter words
					 Sm: "", // Sm letter words
					 Sn: "", // Sn letter words
					 So: "", // So letter words
					 Sp: "", // Sp letter words
					 Sq: "", // Sq letter words
					 Sr: "", // Sr letter words
					 Ss: "", // Ss letter words
					 St: "", // St letter words
					 Su: "", // Su letter words
					 Sv: "", // Sv letter words
					 Sw: "", // Sw letter words
					 Sx: "", // Sx letter words
					 Sy: "", // Sy letter words
					 Sz: "", // Sz letter words
					 TA: "", // TA letter words
					 TB: "", // TB letter words
					 TC: "", // TC letter words
					 TD: "", // TD letter words
					 TE: "", // TE letter words
					 TF: "", // TF letter words
					 TG: "", // TG letter words
					 TH: "", // TH letter words
					 TI: "", // TI letter words
					 TJ: "", // TJ letter words
					 TK: "", // TK letter words
					 TL: "", // TL letter words
					 TM: "", // TM letter words
					 TN: "", // TN letter words
					 TO: "", // TO letter words
					 TP: "", // TP letter words
					 TQ: "", // TQ letter words
					 TR: "", // TR letter words
					 TS: "", // TS letter words
					 TT: "", // TT letter words
					 TU: "", // TU letter words
					 TV: "", // TV letter words
					 TW: "", // TW letter words
					 TX: "", // TX letter words
					 TY: "", // TY letter words
					 TZ: "", // TZ letter words
					 Ta: "", // Ta letter words
					 Tb: "", // Tb letter words
					 Tc: "", // Tc letter words
					 Td: "", // Td letter words
					 Te: "", // Te letter words
					 Tf: "", // Tf letter words
					 Tg: "", // Tg letter words
					 Th: "", // Th letter words
					 Ti: "", // Ti letter words
					 Tj: "", // Tj letter words
					 Tk: "", // Tk letter words
					 Tl: "", // Tl letter words
					 Tm: "", // Tm letter words
					 Tn: "", // Tn letter words
					 To: "", // To letter words
					 Tp: "", // Tp letter words
					 Tq: "", // Tq letter words
					 Tr: "", // Tr letter words
					 Ts: "", // Ts letter words
					 Tt: "", // Tt letter words
					 Tu: "", // Tu letter words
					 Tv: "", // Tv letter words
					 Tw: "", // Tw letter words
					 Tx: "", // Tx letter words
					 Ty: "", // Ty letter words
					 Tz: "", // Tz letter words
					 UA: "", // UA letter words
					 UB: "", // UB letter words
					 UC: "", // UC letter words
					 UD: "", // UD letter words
					 UE: "", // UE letter words
					 UF: "", // UF letter words
					 UG: "", // UG letter words
					 UH: "", // UH letter words
					 UI: "", // UI letter words
					 UJ: "", // UJ letter words
					 UK: "", // UK letter words
					 UL: "", // UL letter words
					 UM: "", // UM letter words
					 UN: "", // UN letter words
					 UO: "", // UO letter words
					 UP: "", // UP letter words
					 UQ: "", // UQ letter words
					 UR: "", // UR letter words
					 US: "", // US letter words
					 UT: "", // UT letter words
					 UU: "", // UU letter words
					 UV: "", // UV letter words
					 UW: "", // UW letter words
					 UX: "", // UX letter words
					 UY: "", // UY letter words
					 UZ: "", // UZ letter words
					 Ua: "", // Ua letter words
					 Ub: "", // Ub letter words
					 Uc: "", // Uc letter words
					 Ud: "", // Ud letter words
					 Ue: "", // Ue letter words
					 Uf: "", // Uf letter words
					 Ug: "", // Ug letter words
					 Uh: "", // Uh letter words
					 Ui: "", // Ui letter words
					 Uj: "", // Uj letter words
					 Uk: "", // Uk letter words
					 Ul: "", // Ul letter words
					 Um: "", // Um letter words
					 Un: "", // Un letter words
					 Uo: "", // Uo letter words
					 Up: "", // Up letter words
					 Uq: "", // Uq letter words
					 Ur: "", // Ur letter words
					 Us: "", // Us letter words
					 Ut: "", // Ut letter words
					 Uu: "", // Uu letter words
					 Uv: "", // Uv letter words
					 Uw: "", // Uw letter words
					 Ux: "", // Ux letter words
					 Uy: "", // Uy letter words
					 Uz: "", // Uz letter words
					 VA: "", // VA letter words
					 VB: "", // VB letter words
					 VC: "", // VC letter words
					 VD: "", // VD letter words
					 VE: "", // VE letter words
					 VF: "", // VF letter words
					 VG: "", // VG letter words
					 VH: "", // VH letter words
					 VI: "", // VI letter words
					 VJ: "", // VJ letter words
					 VK: "", // VK letter words
					 VL: "", // VL letter words
					 VM: "", // VM letter words
					 VN: "", // VN letter words
					 VO: "", // VO letter words
					 VP: "", // VP letter words
					 VQ: "", // VQ letter words
					 VR: "", // VR letter words
					 VS: "", // VS letter words
					 VT: "", // VT letter words
					 VU: "", // VU letter words
					 VV: "", // VV letter words
					 VW: "", // VW letter words
					 VX: "", // VX letter words
					 VY: "", // VY letter words
					 VZ: "", // VZ letter words
					 Va: "", // Va letter words
					 Vb: "", // Vb letter words
					 Vc: "", // Vc letter words
					 Vd: "", // Vd letter words
					 Ve: "", // Ve letter words
					 Vf: "", // Vf letter words
					 Vg: "", // Vg letter words
					 Vh: "", // Vh letter words
					 Vi: "", // Vi letter words
					 Vj: "", // Vj letter words
					 Vk: "", // Vk letter words
					 Vl: "", // Vl letter words
					 Vm: "", // Vm letter words
					 Vn: "", // Vn letter words
					 Vo: "", // Vo letter words
					 Vp: "", // Vp letter words
					 Vq: "", // Vq letter words
					 Vr: "", // Vr letter words
					 Vs: "", // Vs letter words
					 Vt: "", // Vt letter words
					 Vu: "", // Vu letter words
					 Vv: "", // Vv letter words
					 Vw: "", // Vw letter words
					 Vx: "", // Vx letter words
					 Vy: "", // Vy letter words
					 Vz: "", // Vz letter words
					 WA: "", // WA letter words
					 WB: "", // WB letter words
					 WC: "", // WC letter words
					 WD: "", // WD letter words
					 WE: "", // WE letter words
					 WF: "", // WF letter words
					 WG: "", // WG letter words
					 WH: "", // WH letter words
					 WI: "", // WI letter words
					 WJ: "", // WJ letter words
					 WK: "", // WK letter words
					 WL: "", // WL letter words
					 WM: "", // WM letter words
					 WN: "", // WN letter words
					 WO: "", // WO letter words
					 WP: "", // WP letter words
					 WQ: "", // WQ letter words
					 WR: "", // WR letter words
					 WS: "", // WS letter words
					 WT: "", // WT letter words
					 WU: "", // WU letter words
					 WV: "", // WV letter words
					 WW: "", // WW letter words
					 WX: "", // WX letter words
					 WY: "", // WY letter words
					 WZ: "", // WZ letter words
					 Wa: "", // Wa letter words
					 Wb: "", // Wb letter words
					 Wc: "", // Wc letter words
					 Wd: "", // Wd letter words
					 We: "", // We letter words
					 Wf: "", // Wf letter words
					 Wg: "", // Wg letter words
					 Wh: "", // Wh letter words
					 Wi: "", // Wi letter words
					 Wj: "", // Wj letter words
					 Wk: "", // Wk letter words
					 Wl: "", // Wl letter words
					 Wm: "", // Wm letter words
					 Wn: "", // Wn letter words
					 Wo: "", // Wo letter words
					 Wp: "", // Wp letter words
					 Wq: "", // Wq letter words
					 Wr: "", // Wr letter words
					 Ws: "", // Ws letter words
					 Wt: "", // Wt letter words
					 Wu: "", // Wu letter words
					 Wv: "", // Wv letter words
					 Ww: "", // Ww letter words
					 Wx: "", // Wx letter words
					 Wy: "", // Wy letter words
					 Wz: "", // Wz letter words
					 XA: "", // XA letter words
					 XB: "", // XB letter words
					 XC: "", // XC letter words
					 XD: "", // XD letter words
					 XE: "", // XE letter words
					 XF: "", // XF letter words
					 XG: "", // XG letter words
					 XH: "", // XH letter words
					 XI: "", // XI letter words
					 XJ: "", // XJ letter words
					 XK: "", // XK letter words
					 XL: "", // XL letter words
					 XM: "", // XM letter words
					 XN: "", // XN letter words
					 XO: "", // XO letter words
					 XP: "", // XP letter words
					 XQ: "", // XQ letter words
					 XR: "", // XR letter words
					 XS: "", // XS letter words
					 XT: "", // XT letter words
					 XU: "", // XU letter words
					 XV: "", // XV letter words
					 XW: "", // XW letter words
					 XX: "", // XX letter words
					 XY: "", // XY letter words
					 XZ: "", // XZ letter words
					 Xa: "", // Xa letter words
					 Xb: "", // Xb letter words
					 Xc: "", // Xc letter words
					 Xd: "", // Xd letter words
					 Xe: "", // Xe letter words
					 Xf: "", // Xf letter words
					 Xg: "", // Xg letter words
					 Xh: "", // Xh letter words
					 Xi: "", // Xi letter words
					 Xj: "", // Xj letter words
					 Xk: "", // Xk letter words
					 Xl: "", // Xl letter words
					 Xm: "", // Xm letter words
					 Xn: "", // Xn letter words
					 Xo: "", // Xo letter words
					 Xp: "", // Xp letter words
					 Xq: "", // Xq letter words
					 Xr: "", // Xr letter words
					 Xs: "", // Xs letter words
					 Xt: "", // Xt letter words
					 Xu: "", // Xu letter words
					 Xv: "", // Xv letter words
					 Xw: "", // Xw letter words
					 Xx: "", // Xx letter words
					 Xy: "", // Xy letter words
					 Xz: "", // Xz letter words
					 YA: "", // YA letter words
					 YB: "", // YB letter words
					 YC: "", // YC letter words
					 YD: "", // YD letter words
					 YE: "", // YE letter words
					 YF: "", // YF letter words
					 YG: "", // YG letter words
					 YH: "", // YH letter words
					 YI: "", // YI letter words
					 YJ: "", // YJ letter words
					 YK: "", // YK letter words
					 YL: "", // YL letter words
					 YM: "", // YM letter words
					 YN: "", // YN letter words
					 YO: "", // YO letter words
					 YP: "", // YP letter words
					 YQ: "", // YQ letter words
					 YR: "", // YR letter words
					 YS: "", // YS letter words
					 YT: "", // YT letter words
					 YU: "", // YU letter words
					 YV: "", // YV letter words
					 YW: "", // YW letter words
					 YX: "", // YX letter words
					 YY: "", // YY letter words
					 YZ: "", // YZ letter words
					 Ya: "", // Ya letter words
					 Yb: "", // Yb letter words
					 Yc: "", // Yc letter words
					 Yd: "", // Yd letter words
					 Ye: "", // Ye letter words
					 Yf: "", // Yf letter words
					 Yg: "", // Yg letter words
					 Yh: "", // Yh letter words
					 Yi: "", // Yi letter words
					 Yj: "", // Yj letter words
					 Yk: "", // Yk letter words
					 Yl: "", // Yl letter words
					 Ym: "", // Ym letter words
					 Yn: "", // Yn letter words
					 Yo: "", // Yo letter words
					 Yp: "", // Yp letter words
					 Yq: "", // Yq letter words
					 Yr: "", // Yr letter words
					 Ys: "", // Ys letter words
					 Yt: "", // Yt letter words
					 Yu: "", // Yu letter words
					 Yv: "", // Yv letter words
					 Yw: "", // Yw letter words
					 Yx: "", // Yx letter words
					 Yy: "", // Yy letter words
					 Yz: "", // Yz letter words
					 ZA: "", // ZA letter words
					 ZB: "", // ZB letter words
					 ZC: "", // ZC letter words
					 ZD: "", // ZD letter words
					 ZE: "", // ZE letter words
					 ZF: "", // ZF letter words
					 ZG: "", // ZG letter words
					 ZH: "", // ZH letter words
					 ZI: "", // ZI letter words
					 ZJ: "", // ZJ letter words
					 ZK: "", // ZK letter words
					 ZL: "", // ZL letter words
					 ZM: "", // ZM letter words
					 ZN: "", // ZN letter words
					 ZO: "", // ZO letter words
					 ZP: "", // ZP letter words
					 ZQ: "", // ZQ letter words
					 ZR: "", // ZR letter words
					 ZS: "", // ZS letter words
					 ZT: "", // ZT letter words
					 ZU: "", // ZU letter words
					 ZV: "", // ZV letter words
					 ZW: "", // ZW letter words
					 ZX: "", // ZX letter words
					 ZY: "", // ZY letter words
					 ZZ: "", // ZZ letter words
					 Za: "", // Za letter words
					 Zb: "", // Zb letter words
					 Zc: "", // Zc letter words
					 Zd: "", // Zd letter words
					 Ze: "", // Ze letter words
					 Zf: "", // Zf letter words
					 Zg: "", // Zg letter words
					 Zh: "", // Zh letter words
					 Zi: "", // Zi letter words
					 Zj: "", // Zj letter words
					 Zk: "", // Zk letter words
					 Zl: "", // Zl letter words
					 Zm: "", // Zm letter words
					 Zn: "", // Zn letter words
					 Zo: "", // Zo letter words
					 Zp: "", // Zp letter words
					 Zq: "", // Zq letter words
					 Zr: "", // Zr letter words
					 Zs: "", // Zs letter words
					 Zt: "", // Zt letter words
					 Zu: "", // Zu letter words
					 Zv: "", // Zv letter words
					 Zw: "", // Zw letter words
					 Zx: "", // Zx letter words
					 Zy: "", // Zy letter words
					 Zz: "", // Zz letter words
					 aA: "", // aA letter words
					 aB: "", // aB letter words
					 aC: "", // aC letter words
					 aD: "", // aD letter words
					 aE: "", // aE letter words
					 aF: "", // aF letter words
					 aG: "", // aG letter words
					 aH: "", // aH letter words
					 aI: "", // aI letter words
					 aJ: "", // aJ letter words
					 aK: "", // aK letter words
					 aL: "", // aL letter words
					 aM: "", // aM letter words
					 aN: "", // aN letter words
					 aO: "", // aO letter words
					 aP: "", // aP letter words
					 aQ: "", // aQ letter words
					 aR: "", // aR letter words
					 aS: "", // aS letter words
					 aT: "", // aT letter words
					 aU: "", // aU letter words
					 aV: "", // aV letter words
					 aW: "", // aW letter words
					 aX: "", // aX letter words
					 aY: "", // aY letter words
					 aZ: "", // aZ letter words
					 aa: "", // aa letter words
					 ab: "", // ab letter words
					 ac: "", // ac letter words
					 ad: "", // ad letter words
					 ae: "", // ae letter words
					 af: "", // af letter words
					 ag: "", // ag letter words
					 ah: "", // ah letter words
					 ai: "", // ai letter words
					 aj: "", // aj letter words
					 ak: "", // ak letter words
					 al: "", // al letter words
					 am: "", // am letter words
					 an: "", // an letter words
					 ao: "", // ao letter words
					 ap: "", // ap letter words
					 aq: "", // aq letter words
					 ar: "", // ar letter words
					 as: "", // as letter words
					 at: "", // at letter words
					 au: "", // au letter words
					 av: "", // av letter words
					 aw: "", // aw letter words
					 ax: "", // ax letter words
					 ay: "", // ay letter words
					 az: "", // az letter words
					 bA: "", // bA letter words
					 bB: "", // bB letter words
					 bC: "", // bC letter words
					 bD: "", // bD letter words
					 bE: "", // bE letter words
					 bF: "", // bF letter words
					 bG: "", // bG letter words
					 bH: "", // bH letter words
					 bI: "", // bI letter words
					 bJ: "", // bJ letter words
					 bK: "", // bK letter words
					 bL: "", // bL letter words
					 bM: "", // bM letter words
					 bN: "", // bN letter words
					 bO: "", // bO letter words
					 bP: "", // bP letter words
					 bQ: "", // bQ letter words
					 bR: "", // bR letter words
					 bS: "", // bS letter words
					 bT: "", // bT letter words
					 bU: "", // bU letter words
					 bV: "", // bV letter words
					 bW: "", // bW letter words
					 bX: "", // bX letter words
					 bY: "", // bY letter words
					 bZ: "", // bZ letter words
					 ba: "", // ba letter words
					 bb: "", // bb letter words
					 bc: "", // bc letter words
					 bd: "", // bd letter words
					 be: "", // be letter words
					 bf: "", // bf letter words
					 bg: "", // bg letter words
					 bh: "", // bh letter words
					 bi: "", // bi letter words
					 bj: "", // bj letter words
					 bk: "", // bk letter words
					 bl: "", // bl letter words
					 bm: "", // bm letter words
					 bn: "", // bn letter words
					 bo: "", // bo letter words
					 bp: "", // bp letter words
					 bq: "", // bq letter words
					 br: "", // br letter words
					 bs: "", // bs letter words
					 bt: "", // bt letter words
					 bu: "", // bu letter words
					 bv: "", // bv letter words
					 bw: "", // bw letter words
					 bx: "", // bx letter words
					 by: "", // by letter words
					 bz: "", // bz letter words
					 cA: "", // cA letter words
					 cB: "", // cB letter words
					 cC: "", // cC letter words
					 cD: "", // cD letter words
					 cE: "", // cE letter words
					 cF: "", // cF letter words
					 cG: "", // cG letter words
					 cH: "", // cH letter words
					 cI: "", // cI letter words
					 cJ: "", // cJ letter words
					 cK: "", // cK letter words
					 cL: "", // cL letter words
					 cM: "", // cM letter words
					 cN: "", // cN letter words
					 cO: "", // cO letter words
					 cP: "", // cP letter words
					 cQ: "", // cQ letter words
					 cR: "", // cR letter words
					 cS: "", // cS letter words
					 cT: "", // cT letter words
					 cU: "", // cU letter words
					 cV: "", // cV letter words
					 cW: "", // cW letter words
					 cX: "", // cX letter words
					 cY: "", // cY letter words
					 cZ: "", // cZ letter words
					 ca: "", // ca letter words
					 cb: "", // cb letter words
					 cc: "", // cc letter words
					 cd: "", // cd letter words
					 ce: "", // ce letter words
					 cf: "", // cf letter words
					 cg: "", // cg letter words
					 ch: "", // ch letter words
					 ci: "", // ci letter words
					 cj: "", // cj letter words
					 ck: "", // ck letter words
					 cl: "", // cl letter words
					 cm: "", // cm letter words
					 cn: "", // cn letter words
					 co: "", // co letter words
					 cp: "", // cp letter words
					 cq: "", // cq letter words
					 cr: "", // cr letter words
					 cs: "", // cs letter words
					 ct: "", // ct letter words
					 cu: "", // cu letter words
					 cv: "", // cv letter words
					 cw: "", // cw letter words
					 cx: "", // cx letter words
					 cy: "", // cy letter words
					 cz: "", // cz letter words
					 dA: "", // dA letter words
					 dB: "", // dB letter words
					 dC: "", // dC letter words
					 dD: "", // dD letter words
					 dE: "", // dE letter words
					 dF: "", // dF letter words
					 dG: "", // dG letter words
					 dH: "", // dH letter words
					 dI: "", // dI letter words
					 dJ: "", // dJ letter words
					 dK: "", // dK letter words
					 dL: "", // dL letter words
					 dM: "", // dM letter words
					 dN: "", // dN letter words
					 dO: "", // dO letter words
					 dP: "", // dP letter words
					 dQ: "", // dQ letter words
					 dR: "", // dR letter words
					 dS: "", // dS letter words
					 dT: "", // dT letter words
					 dU: "", // dU letter words
					 dV: "", // dV letter words
					 dW: "", // dW letter words
					 dX: "", // dX letter words
					 dY: "", // dY letter words
					 dZ: "", // dZ letter words
					 da: "", // da letter words
					 db: "", // db letter words
					 dc: "", // dc letter words
					 dd: "", // dd letter words
					 de: "", // de letter words
					 df: "", // df letter words
					 dg: "", // dg letter words
					 dh: "", // dh letter words
					 di: "", // di letter words
					 dj: "", // dj letter words
					 dk: "", // dk letter words
					 dl: "", // dl letter words
					 dm: "", // dm letter words
					 dn: "", // dn letter words
					 do: "", // do letter words
					 dp: "", // dp letter words
					 dq: "", // dq letter words
					 dr: "", // dr letter words
					 ds: "", // ds letter words
					 dt: "", // dt letter words
					 du: "", // du letter words
					 dv: "", // dv letter words
					 dw: "", // dw letter words
					 dx: "", // dx letter words
					 dy: "", // dy letter words
					 dz: "", // dz letter words
					 eA: "", // eA letter words
					 eB: "", // eB letter words
					 eC: "", // eC letter words
					 eD: "", // eD letter words
					 eE: "", // eE letter words
					 eF: "", // eF letter words
					 eG: "", // eG letter words
					 eH: "", // eH letter words
					 eI: "", // eI letter words
					 eJ: "", // eJ letter words
					 eK: "", // eK letter words
					 eL: "", // eL letter words
					 eM: "", // eM letter words
					 eN: "", // eN letter words
					 eO: "", // eO letter words
					 eP: "", // eP letter words
					 eQ: "", // eQ letter words
					 eR: "", // eR letter words
					 eS: "", // eS letter words
					 eT: "", // eT letter words
					 eU: "", // eU letter words
					 eV: "", // eV letter words
					 eW: "", // eW letter words
					 eX: "", // eX letter words
					 eY: "", // eY letter words
					 eZ: "", // eZ letter words
					 ea: "", // ea letter words
					 eb: "", // eb letter words
					 ec: "", // ec letter words
					 ed: "", // ed letter words
					 ee: "", // ee letter words
					 ef: "", // ef letter words
					 eg: "", // eg letter words
					 eh: "", // eh letter words
					 ei: "", // ei letter words
					 ej: "", // ej letter words
					 ek: "", // ek letter words
					 el: "", // el letter words
					 em: "", // em letter words
					 en: "", // en letter words
					 eo: "", // eo letter words
					 ep: "", // ep letter words
					 eq: "", // eq letter words
					 er: "", // er letter words
					 es: "", // es letter words
					 et: "", // et letter words
					 eu: "", // eu letter words
					 ev: "", // ev letter words
					 ew: "", // ew letter words
					 ex: "", // ex letter words
					 ey: "", // ey letter words
					 ez: "", // ez letter words
					 fA: "", // fA letter words
					 fB: "", // fB letter words
					 fC: "", // fC letter words
					 fD: "", // fD letter words
					 fE: "", // fE letter words
					 fF: "", // fF letter words
					 fG: "", // fG letter words
					 fH: "", // fH letter words
					 fI: "", // fI letter words
					 fJ: "", // fJ letter words
					 fK: "", // fK letter words
					 fL: "", // fL letter words
					 fM: "", // fM letter words
					 fN: "", // fN letter words
					 fO: "", // fO letter words
					 fP: "", // fP letter words
					 fQ: "", // fQ letter words
					 fR: "", // fR letter words
					 fS: "", // fS letter words
					 fT: "", // fT letter words
					 fU: "", // fU letter words
					 fV: "", // fV letter words
					 fW: "", // fW letter words
					 fX: "", // fX letter words
					 fY: "", // fY letter words
					 fZ: "", // fZ letter words
					 fa: "", // fa letter words
					 fb: "", // fb letter words
					 fc: "", // fc letter words
					 fd: "", // fd letter words
					 fe: "", // fe letter words
					 ff: "", // ff letter words
					 fg: "", // fg letter words
					 fh: "", // fh letter words
					 fi: "", // fi letter words
					 fj: "", // fj letter words
					 fk: "", // fk letter words
					 fl: "", // fl letter words
					 fm: "", // fm letter words
					 fn: "", // fn letter words
					 fo: "", // fo letter words
					 fp: "", // fp letter words
					 fq: "", // fq letter words
					 fr: "", // fr letter words
					 fs: "", // fs letter words
					 ft: "", // ft letter words
					 fu: "", // fu letter words
					 fv: "", // fv letter words
					 fw: "", // fw letter words
					 fx: "", // fx letter words
					 fy: "", // fy letter words
					 fz: "", // fz letter words
					 gA: "", // gA letter words
					 gB: "", // gB letter words
					 gC: "", // gC letter words
					 gD: "", // gD letter words
					 gE: "", // gE letter words
					 gF: "", // gF letter words
					 gG: "", // gG letter words
					 gH: "", // gH letter words
					 gI: "", // gI letter words
					 gJ: "", // gJ letter words
					 gK: "", // gK letter words
					 gL: "", // gL letter words
					 gM: "", // gM letter words
					 gN: "", // gN letter words
					 gO: "", // gO letter words
					 gP: "", // gP letter words
					 gQ: "", // gQ letter words
					 gR: "", // gR letter words
					 gS: "", // gS letter words
					 gT: "", // gT letter words
					 gU: "", // gU letter words
					 gV: "", // gV letter words
					 gW: "", // gW letter words
					 gX: "", // gX letter words
					 gY: "", // gY letter words
					 gZ: "", // gZ letter words
					 ga: "", // ga letter words
					 gb: "", // gb letter words
					 gc: "", // gc letter words
					 gd: "", // gd letter words
					 ge: "", // ge letter words
					 gf: "", // gf letter words
					 gg: "", // gg letter words
					 gh: "", // gh letter words
					 gi: "", // gi letter words
					 gj: "", // gj letter words
					 gk: "", // gk letter words
					 gl: "", // gl letter words
					 gm: "", // gm letter words
					 gn: "", // gn letter words
					 go: "", // go letter words
					 gp: "", // gp letter words
					 gq: "", // gq letter words
					 gr: "", // gr letter words
					 gs: "", // gs letter words
					 gt: "", // gt letter words
					 gu: "", // gu letter words
					 gv: "", // gv letter words
					 gw: "", // gw letter words
					 gx: "", // gx letter words
					 gy: "", // gy letter words
					 gz: "", // gz letter words
					 hA: "", // hA letter words
					 hB: "", // hB letter words
					 hC: "", // hC letter words
					 hD: "", // hD letter words
					 hE: "", // hE letter words
					 hF: "", // hF letter words
					 hG: "", // hG letter words
					 hH: "", // hH letter words
					 hI: "", // hI letter words
					 hJ: "", // hJ letter words
					 hK: "", // hK letter words
					 hL: "", // hL letter words
					 hM: "", // hM letter words
					 hN: "", // hN letter words
					 hO: "", // hO letter words
					 hP: "", // hP letter words
					 hQ: "", // hQ letter words
					 hR: "", // hR letter words
					 hS: "", // hS letter words
					 hT: "", // hT letter words
					 hU: "", // hU letter words
					 hV: "", // hV letter words
					 hW: "", // hW letter words
					 hX: "", // hX letter words
					 hY: "", // hY letter words
					 hZ: "", // hZ letter words
					 ha: "", // ha letter words
					 hb: "", // hb letter words
					 hc: "", // hc letter words
					 hd: "", // hd letter words
					 he: "", // he letter words
					 hf: "", // hf letter words
					 hg: "", // hg letter words
					 hh: "", // hh letter words
					 hi: "", // hi letter words
					 hj: "", // hj letter words
					 hk: "", // hk letter words
					 hl: "", // hl letter words
					 hm: "", // hm letter words
					 hn: "", // hn letter words
					 ho: "", // ho letter words
					 hp: "", // hp letter words
					 hq: "", // hq letter words
					 hr: "", // hr letter words
					 hs: "", // hs letter words
					 ht: "", // ht letter words
					 hu: "", // hu letter words
					 hv: "", // hv letter words
					 hw: "", // hw letter words
					 hx: "", // hx letter words
					 hy: "", // hy letter words
					 hz: "", // hz letter words
					 iA: "", // iA letter words
					 iB: "", // iB letter words
					 iC: "", // iC letter words
					 iD: "", // iD letter words
					 iE: "", // iE letter words
					 iF: "", // iF letter words
					 iG: "", // iG letter words
					 iH: "", // iH letter words
					 iI: "", // iI letter words
					 iJ: "", // iJ letter words
					 iK: "", // iK letter words
					 iL: "", // iL letter words
					 iM: "", // iM letter words
					 iN: "", // iN letter words
					 iO: "", // iO letter words
					 iP: "", // iP letter words
					 iQ: "", // iQ letter words
					 iR: "", // iR letter words
					 iS: "", // iS letter words
					 iT: "", // iT letter words
					 iU: "", // iU letter words
					 iV: "", // iV letter words
					 iW: "", // iW letter words
					 iX: "", // iX letter words
					 iY: "", // iY letter words
					 iZ: "", // iZ letter words
					 ia: "", // ia letter words
					 ib: "", // ib letter words
					 ic: "", // ic letter words
					 id: "", // id letter words
					 ie: "", // ie letter words
					 if: "", // if letter words
					 ig: "", // ig letter words
					 ih: "", // ih letter words
					 ii: "", // ii letter words
					 ij: "", // ij letter words
					 ik: "", // ik letter words
					 il: "", // il letter words
					 im: "", // im letter words
					 in: "", // in letter words
					 io: "", // io letter words
					 ip: "", // ip letter words
					 iq: "", // iq letter words
					 ir: "", // ir letter words
					 is: "", // is letter words
					 it: "", // it letter words
					 iu: "", // iu letter words
					 iv: "", // iv letter words
					 iw: "", // iw letter words
					 ix: "", // ix letter words
					 iy: "", // iy letter words
					 iz: "", // iz letter words
					 jA: "", // jA letter words
					 jB: "", // jB letter words
					 jC: "", // jC letter words
					 jD: "", // jD letter words
					 jE: "", // jE letter words
					 jF: "", // jF letter words
					 jG: "", // jG letter words
					 jH: "", // jH letter words
					 jI: "", // jI letter words
					 jJ: "", // jJ letter words
					 jK: "", // jK letter words
					 jL: "", // jL letter words
					 jM: "", // jM letter words
					 jN: "", // jN letter words
					 jO: "", // jO letter words
					 jP: "", // jP letter words
					 jQ: "", // jQ letter words
					 jR: "", // jR letter words
					 jS: "", // jS letter words
					 jT: "", // jT letter words
					 jU: "", // jU letter words
					 jV: "", // jV letter words
					 jW: "", // jW letter words
					 jX: "", // jX letter words
					 jY: "", // jY letter words
					 jZ: "", // jZ letter words
					 ja: "", // ja letter words
					 jb: "", // jb letter words
					 jc: "", // jc letter words
					 jd: "", // jd letter words
					 je: "", // je letter words
					 jf: "", // jf letter words
					 jg: "", // jg letter words
					 jh: "", // jh letter words
					 ji: "", // ji letter words
					 jj: "", // jj letter words
					 jk: "", // jk letter words
					 jl: "", // jl letter words
					 jm: "", // jm letter words
					 jn: "", // jn letter words
					 jo: "", // jo letter words
					 jp: "", // jp letter words
					 jq: "", // jq letter words
					 jr: "", // jr letter words
					 js: "", // js letter words
					 jt: "", // jt letter words
					 ju: "", // ju letter words
					 jv: "", // jv letter words
					 jw: "", // jw letter words
					 jx: "", // jx letter words
					 jy: "", // jy letter words
					 jz: "", // jz letter words
					 kA: "", // kA letter words
					 kB: "", // kB letter words
					 kC: "", // kC letter words
					 kD: "", // kD letter words
					 kE: "", // kE letter words
					 kF: "", // kF letter words
					 kG: "", // kG letter words
					 kH: "", // kH letter words
					 kI: "", // kI letter words
					 kJ: "", // kJ letter words
					 kK: "", // kK letter words
					 kL: "", // kL letter words
					 kM: "", // kM letter words
					 kN: "", // kN letter words
					 kO: "", // kO letter words
					 kP: "", // kP letter words
					 kQ: "", // kQ letter words
					 kR: "", // kR letter words
					 kS: "", // kS letter words
					 kT: "", // kT letter words
					 kU: "", // kU letter words
					 kV: "", // kV letter words
					 kW: "", // kW letter words
					 kX: "", // kX letter words
					 kY: "", // kY letter words
					 kZ: "", // kZ letter words
					 ka: "", // ka letter words
					 kb: "", // kb letter words
					 kc: "", // kc letter words
					 kd: "", // kd letter words
					 ke: "", // ke letter words
					 kf: "", // kf letter words
					 kg: "", // kg letter words
					 kh: "", // kh letter words
					 ki: "", // ki letter words
					 kj: "", // kj letter words
					 kk: "", // kk letter words
					 kl: "", // kl letter words
					 km: "", // km letter words
					 kn: "", // kn letter words
					 ko: "", // ko letter words
					 kp: "", // kp letter words
					 kq: "", // kq letter words
					 kr: "", // kr letter words
					 ks: "", // ks letter words
					 kt: "", // kt letter words
					 ku: "", // ku letter words
					 kv: "", // kv letter words
					 kw: "", // kw letter words
					 kx: "", // kx letter words
					 ky: "", // ky letter words
					 kz: "", // kz letter words
					 lA: "", // lA letter words
					 lB: "", // lB letter words
					 lC: "", // lC letter words
					 lD: "", // lD letter words
					 lE: "", // lE letter words
					 lF: "", // lF letter words
					 lG: "", // lG letter words
					 lH: "", // lH letter words
					 lI: "", // lI letter words
					 lJ: "", // lJ letter words
					 lK: "", // lK letter words
					 lL: "", // lL letter words
					 lM: "", // lM letter words
					 lN: "", // lN letter words
					 lO: "", // lO letter words
					 lP: "", // lP letter words
					 lQ: "", // lQ letter words
					 lR: "", // lR letter words
					 lS: "", // lS letter words
					 lT: "", // lT letter words
					 lU: "", // lU letter words
					 lV: "", // lV letter words
					 lW: "", // lW letter words
					 lX: "", // lX letter words
					 lY: "", // lY letter words
					 lZ: "", // lZ letter words
					 la: "", // la letter words
					 lb: "", // lb letter words
					 lc: "", // lc letter words
					 ld: "", // ld letter words
					 le: "", // le letter words
					 lf: "", // lf letter words
					 lg: "", // lg letter words
					 lh: "", // lh letter words
					 li: "", // li letter words
					 lj: "", // lj letter words
					 lk: "", // lk letter words
					 ll: "", // ll letter words
					 lm: "", // lm letter words
					 ln: "", // ln letter words
					 lo: "", // lo letter words
					 lp: "", // lp letter words
					 lq: "", // lq letter words
					 lr: "", // lr letter words
					 ls: "", // ls letter words
					 lt: "", // lt letter words
					 lu: "", // lu letter words
					 lv: "", // lv letter words
					 lw: "", // lw letter words
					 lx: "", // lx letter words
					 ly: "", // ly letter words
					 lz: "", // lz letter words
					 mA: "", // mA letter words
					 mB: "", // mB letter words
					 mC: "", // mC letter words
					 mD: "", // mD letter words
					 mE: "", // mE letter words
					 mF: "", // mF letter words
					 mG: "", // mG letter words
					 mH: "", // mH letter words
					 mI: "", // mI letter words
					 mJ: "", // mJ letter words
					 mK: "", // mK letter words
					 mL: "", // mL letter words
					 mM: "", // mM letter words
					 mN: "", // mN letter words
					 mO: "", // mO letter words
					 mP: "", // mP letter words
					 mQ: "", // mQ letter words
					 mR: "", // mR letter words
					 mS: "", // mS letter words
					 mT: "", // mT letter words
					 mU: "", // mU letter words
					 mV: "", // mV letter words
					 mW: "", // mW letter words
					 mX: "", // mX letter words
					 mY: "", // mY letter words
					 mZ: "", // mZ letter words
					 ma: "", // ma letter words
					 mb: "", // mb letter words
					 mc: "", // mc letter words
					 md: "", // md letter words
					 me: "", // me letter words
					 mf: "", // mf letter words
					 mg: "", // mg letter words
					 mh: "", // mh letter words
					 mi: "", // mi letter words
					 mj: "", // mj letter words
					 mk: "", // mk letter words
					 ml: "", // ml letter words
					 mm: "", // mm letter words
					 mn: "", // mn letter words
					 mo: "", // mo letter words
					 mp: "", // mp letter words
					 mq: "", // mq letter words
					 mr: "", // mr letter words
					 ms: "", // ms letter words
					 mt: "", // mt letter words
					 mu: "", // mu letter words
					 mv: "", // mv letter words
					 mw: "", // mw letter words
					 mx: "", // mx letter words
					 my: "", // my letter words
					 mz: "", // mz letter words
					 nA: "", // nA letter words
					 nB: "", // nB letter words
					 nC: "", // nC letter words
					 nD: "", // nD letter words
					 nE: "", // nE letter words
					 nF: "", // nF letter words
					 nG: "", // nG letter words
					 nH: "", // nH letter words
					 nI: "", // nI letter words
					 nJ: "", // nJ letter words
					 nK: "", // nK letter words
					 nL: "", // nL letter words
					 nM: "", // nM letter words
					 nN: "", // nN letter words
					 nO: "", // nO letter words
					 nP: "", // nP letter words
					 nQ: "", // nQ letter words
					 nR: "", // nR letter words
					 nS: "", // nS letter words
					 nT: "", // nT letter words
					 nU: "", // nU letter words
					 nV: "", // nV letter words
					 nW: "", // nW letter words
					 nX: "", // nX letter words
					 nY: "", // nY letter words
					 nZ: "", // nZ letter words
					 na: "", // na letter words
					 nb: "", // nb letter words
					 nc: "", // nc letter words
					 nd: "", // nd letter words
					 ne: "", // ne letter words
					 nf: "", // nf letter words
					 ng: "", // ng letter words
					 nh: "", // nh letter words
					 ni: "", // ni letter words
					 nj: "", // nj letter words
					 nk: "", // nk letter words
					 nl: "", // nl letter words
					 nm: "", // nm letter words
					 nn: "", // nn letter words
					 no: "", // no letter words
					 np: "", // np letter words
					 nq: "", // nq letter words
					 nr: "", // nr letter words
					 ns: "", // ns letter words
					 nt: "", // nt letter words
					 nu: "", // nu letter words
					 nv: "", // nv letter words
					 nw: "", // nw letter words
					 nx: "", // nx letter words
					 ny: "", // ny letter words
					 nz: "", // nz letter words
					 oA: "", // oA letter words
					 oB: "", // oB letter words
					 oC: "", // oC letter words
					 oD: "", // oD letter words
					 oE: "", // oE letter words
					 oF: "", // oF letter words
					 oG: "", // oG letter words
					 oH: "", // oH letter words
					 oI: "", // oI letter words
					 oJ: "", // oJ letter words
					 oK: "", // oK letter words
					 oL: "", // oL letter words
					 oM: "", // oM letter words
					 oN: "", // oN letter words
					 oO: "", // oO letter words
					 oP: "", // oP letter words
					 oQ: "", // oQ letter words
					 oR: "", // oR letter words
					 oS: "", // oS letter words
					 oT: "", // oT letter words
					 oU: "", // oU letter words
					 oV: "", // oV letter words
					 oW: "", // oW letter words
					 oX: "", // oX letter words
					 oY: "", // oY letter words
					 oZ: "", // oZ letter words
					 oa: "", // oa letter words
					 ob: "", // ob letter words
					 oc: "", // oc letter words
					 od: "", // od letter words
					 oe: "", // oe letter words
					 of: "", // of letter words
					 og: "", // og letter words
					 oh: "", // oh letter words
					 oi: "", // oi letter words
					 oj: "", // oj letter words
					 ok: "", // ok letter words
					 ol: "", // ol letter words
					 om: "", // om letter words
					 on: "", // on letter words
					 oo: "", // oo letter words
					 op: "", // op letter words
					 oq: "", // oq letter words
					 or: "", // or letter words
					 os: "", // os letter words
					 ot: "", // ot letter words
					 ou: "", // ou letter words
					 ov: "", // ov letter words
					 ow: "", // ow letter words
					 ox: "", // ox letter words
					 oy: "", // oy letter words
					 oz: "", // oz letter words
					 pA: "", // pA letter words
					 pB: "", // pB letter words
					 pC: "", // pC letter words
					 pD: "", // pD letter words
					 pE: "", // pE letter words
					 pF: "", // pF letter words
					 pG: "", // pG letter words
					 pH: "", // pH letter words
					 pI: "", // pI letter words
					 pJ: "", // pJ letter words
					 pK: "", // pK letter words
					 pL: "", // pL letter words
					 pM: "", // pM letter words
					 pN: "", // pN letter words
					 pO: "", // pO letter words
					 pP: "", // pP letter words
					 pQ: "", // pQ letter words
					 pR: "", // pR letter words
					 pS: "", // pS letter words
					 pT: "", // pT letter words
					 pU: "", // pU letter words
					 pV: "", // pV letter words
					 pW: "", // pW letter words
					 pX: "", // pX letter words
					 pY: "", // pY letter words
					 pZ: "", // pZ letter words
					 pa: "", // pa letter words
					 pb: "", // pb letter words
					 pc: "", // pc letter words
					 pd: "", // pd letter words
					 pe: "", // pe letter words
					 pf: "", // pf letter words
					 pg: "", // pg letter words
					 ph: "", // ph letter words
					 pi: "", // pi letter words
					 pj: "", // pj letter words
					 pk: "", // pk letter words
					 pl: "", // pl letter words
					 pm: "", // pm letter words
					 pn: "", // pn letter words
					 po: "", // po letter words
					 pp: "", // pp letter words
					 pq: "", // pq letter words
					 pr: "", // pr letter words
					 ps: "", // ps letter words
					 pt: "", // pt letter words
					 pu: "", // pu letter words
					 pv: "", // pv letter words
					 pw: "", // pw letter words
					 px: "", // px letter words
					 py: "", // py letter words
					 pz: "", // pz letter words
					 qA: "", // qA letter words
					 qB: "", // qB letter words
					 qC: "", // qC letter words
					 qD: "", // qD letter words
					 qE: "", // qE letter words
					 qF: "", // qF letter words
					 qG: "", // qG letter words
					 qH: "", // qH letter words
					 qI: "", // qI letter words
					 qJ: "", // qJ letter words
					 qK: "", // qK letter words
					 qL: "", // qL letter words
					 qM: "", // qM letter words
					 qN: "", // qN letter words
					 qO: "", // qO letter words
					 qP: "", // qP letter words
					 qQ: "", // qQ letter words
					 qR: "", // qR letter words
					 qS: "", // qS letter words
					 qT: "", // qT letter words
					 qU: "", // qU letter words
					 qV: "", // qV letter words
					 qW: "", // qW letter words
					 qX: "", // qX letter words
					 qY: "", // qY letter words
					 qZ: "", // qZ letter words
					 qa: "", // qa letter words
					 qb: "", // qb letter words
					 qc: "", // qc letter words
					 qd: "", // qd letter words
					 qe: "", // qe letter words
					 qf: "", // qf letter words
					 qg: "", // qg letter words
					 qh: "", // qh letter words
					 qi: "", // qi letter words
					 qj: "", // qj letter words
					 qk: "", // qk letter words
					 ql: "", // ql letter words
					 qm: "", // qm letter words
					 qn: "", // qn letter words
					 qo: "", // qo letter words
					 qp: "", // qp letter words
					 qq: "", // qq letter words
					 qr: "", // qr letter words
					 qs: "", // qs letter words
					 qt: "", // qt letter words
					 qu: "", // qu letter words
					 qv: "", // qv letter words
					 qw: "", // qw letter words
					 qx: "", // qx letter words
					 qy: "", // qy letter words
					 qz: "", // qz letter words
					 rA: "", // rA letter words
					 rB: "", // rB letter words
					 rC: "", // rC letter words
					 rD: "", // rD letter words
					 rE: "", // rE letter words
					 rF: "", // rF letter words
					 rG: "", // rG letter words
					 rH: "", // rH letter words
					 rI: "", // rI letter words
					 rJ: "", // rJ letter words
					 rK: "", // rK letter words
					 rL: "", // rL letter words
					 rM: "", // rM letter words
					 rN: "", // rN letter words
					 rO: "", // rO letter words
					 rP: "", // rP letter words
					 rQ: "", // rQ letter words
					 rR: "", // rR letter words
					 rS: "", // rS letter words
					 rT: "", // rT letter words
					 rU: "", // rU letter words
					 rV: "", // rV letter words
					 rW: "", // rW letter words
					 rX: "", // rX letter words
					 rY: "", // rY letter words
					 rZ: "", // rZ letter words
					 ra: "", // ra letter words
					 rb: "", // rb letter words
					 rc: "", // rc letter words
					 rd: "", // rd letter words
					 re: "", // re letter words
					 rf: "", // rf letter words
					 rg: "", // rg letter words
					 rh: "", // rh letter words
					 ri: "", // ri letter words
					 rj: "", // rj letter words
					 rk: "", // rk letter words
					 rl: "", // rl letter words
					 rm: "", // rm letter words
					 rn: "", // rn letter words
					 ro: "", // ro letter words
					 rp: "", // rp letter words
					 rq: "", // rq letter words
					 rr: "", // rr letter words
					 rs: "", // rs letter words
					 rt: "", // rt letter words
					 ru: "", // ru letter words
					 rv: "", // rv letter words
					 rw: "", // rw letter words
					 rx: "", // rx letter words
					 ry: "", // ry letter words
					 rz: "", // rz letter words
					 sA: "", // sA letter words
					 sB: "", // sB letter words
					 sC: "", // sC letter words
					 sD: "", // sD letter words
					 sE: "", // sE letter words
					 sF: "", // sF letter words
					 sG: "", // sG letter words
					 sH: "", // sH letter words
					 sI: "", // sI letter words
					 sJ: "", // sJ letter words
					 sK: "", // sK letter words
					 sL: "", // sL letter words
					 sM: "", // sM letter words
					 sN: "", // sN letter words
					 sO: "", // sO letter words
					 sP: "", // sP letter words
					 sQ: "", // sQ letter words
					 sR: "", // sR letter words
					 sS: "", // sS letter words
					 sT: "", // sT letter words
					 sU: "", // sU letter words
					 sV: "", // sV letter words
					 sW: "", // sW letter words
					 sX: "", // sX letter words
					 sY: "", // sY letter words
					 sZ: "", // sZ letter words
					 sa: "", // sa letter words
					 sb: "", // sb letter words
					 sc: "", // sc letter words
					 sd: "", // sd letter words
					 se: "", // se letter words
					 sf: "", // sf letter words
					 sg: "", // sg letter words
					 sh: "", // sh letter words
					 si: "", // si letter words
					 sj: "", // sj letter words
					 sk: "", // sk letter words
					 sl: "", // sl letter words
					 sm: "", // sm letter words
					 sn: "", // sn letter words
					 so: "", // so letter words
					 sp: "", // sp letter words
					 sq: "", // sq letter words
					 sr: "", // sr letter words
					 ss: "", // ss letter words
					 st: "", // st letter words
					 su: "", // su letter words
					 sv: "", // sv letter words
					 sw: "", // sw letter words
					 sx: "", // sx letter words
					 sy: "", // sy letter words
					 sz: "", // sz letter words
					 tA: "", // tA letter words
					 tB: "", // tB letter words
					 tC: "", // tC letter words
					 tD: "", // tD letter words
					 tE: "", // tE letter words
					 tF: "", // tF letter words
					 tG: "", // tG letter words
					 tH: "", // tH letter words
					 tI: "", // tI letter words
					 tJ: "", // tJ letter words
					 tK: "", // tK letter words
					 tL: "", // tL letter words
					 tM: "", // tM letter words
					 tN: "", // tN letter words
					 tO: "", // tO letter words
					 tP: "", // tP letter words
					 tQ: "", // tQ letter words
					 tR: "", // tR letter words
					 tS: "", // tS letter words
					 tT: "", // tT letter words
					 tU: "", // tU letter words
					 tV: "", // tV letter words
					 tW: "", // tW letter words
					 tX: "", // tX letter words
					 tY: "", // tY letter words
					 tZ: "", // tZ letter words
					 ta: "", // ta letter words
					 tb: "", // tb letter words
					 tc: "", // tc letter words
					 td: "", // td letter words
					 te: "", // te letter words
					 tf: "", // tf letter words
					 tg: "", // tg letter words
					 th: "", // th letter words
					 ti: "", // ti letter words
					 tj: "", // tj letter words
					 tk: "", // tk letter words
					 tl: "", // tl letter words
					 tm: "", // tm letter words
					 tn: "", // tn letter words
					 to: "", // to letter words
					 tp: "", // tp letter words
					 tq: "", // tq letter words
					 tr: "", // tr letter words
					 ts: "", // ts letter words
					 tt: "", // tt letter words
					 tu: "", // tu letter words
					 tv: "", // tv letter words
					 tw: "", // tw letter words
					 tx: "", // tx letter words
					 ty: "", // ty letter words
					 tz: "", // tz letter words
					 uA: "", // uA letter words
					 uB: "", // uB letter words
					 uC: "", // uC letter words
					 uD: "", // uD letter words
					 uE: "", // uE letter words
					 uF: "", // uF letter words
					 uG: "", // uG letter words
					 uH: "", // uH letter words
					 uI: "", // uI letter words
					 uJ: "", // uJ letter words
					 uK: "", // uK letter words
					 uL: "", // uL letter words
					 uM: "", // uM letter words
					 uN: "", // uN letter words
					 uO: "", // uO letter words
					 uP: "", // uP letter words
					 uQ: "", // uQ letter words
					 uR: "", // uR letter words
					 uS: "", // uS letter words
					 uT: "", // uT letter words
					 uU: "", // uU letter words
					 uV: "", // uV letter words
					 uW: "", // uW letter words
					 uX: "", // uX letter words
					 uY: "", // uY letter words
					 uZ: "", // uZ letter words
					 ua: "", // ua letter words
					 ub: "", // ub letter words
					 uc: "", // uc letter words
					 ud: "", // ud letter words
					 ue: "", // ue letter words
					 uf: "", // uf letter words
					 ug: "", // ug letter words
					 uh: "", // uh letter words
					 ui: "", // ui letter words
					 uj: "", // uj letter words
					 uk: "", // uk letter words
					 ul: "", // ul letter words
					 um: "", // um letter words
					 un: "", // un letter words
					 uo: "", // uo letter words
					 up: "", // up letter words
					 uq: "", // uq letter words
					 ur: "", // ur letter words
					 us: "", // us letter words
					 ut: "", // ut letter words
					 uu: "", // uu letter words
					 uv: "", // uv letter words
					 uw: "", // uw letter words
					 ux: "", // ux letter words
					 uy: "", // uy letter words
					 uz: "", // uz letter words
					 vA: "", // vA letter words
					 vB: "", // vB letter words
					 vC: "", // vC letter words
					 vD: "", // vD letter words
					 vE: "", // vE letter words
					 vF: "", // vF letter words
					 vG: "", // vG letter words
					 vH: "", // vH letter words
					 vI: "", // vI letter words
					 vJ: "", // vJ letter words
					 vK: "", // vK letter words
					 vL: "", // vL letter words
					 vM: "", // vM letter words
					 vN: "", // vN letter words
					 vO: "", // vO letter words
					 vP: "", // vP letter words
					 vQ: "", // vQ letter words
					 vR: "", // vR letter words
					 vS: "", // vS letter words
					 vT: "", // vT letter words
					 vU: "", // vU letter words
					 vV: "", // vV letter words
					 vW: "", // vW letter words
					 vX: "", // vX letter words
					 vY: "", // vY letter words
					 vZ: "", // vZ letter words
					 va: "", // va letter words
					 vb: "", // vb letter words
					 vc: "", // vc letter words
					 vd: "", // vd letter words
					 ve: "", // ve letter words
					 vf: "", // vf letter words
					 vg: "", // vg letter words
					 vh: "", // vh letter words
					 vi: "", // vi letter words
					 vj: "", // vj letter words
					 vk: "", // vk letter words
					 vl: "", // vl letter words
					 vm: "", // vm letter words
					 vn: "", // vn letter words
					 vo: "", // vo letter words
					 vp: "", // vp letter words
					 vq: "", // vq letter words
					 vr: "", // vr letter words
					 vs: "", // vs letter words
					 vt: "", // vt letter words
					 vu: "", // vu letter words
					 vv: "", // vv letter words
					 vw: "", // vw letter words
					 vx: "", // vx letter words
					 vy: "", // vy letter words
					 vz: "", // vz letter words
					 wA: "", // wA letter words
					 wB: "", // wB letter words
					 wC: "", // wC letter words
					 wD: "", // wD letter words
					 wE: "", // wE letter words
					 wF: "", // wF letter words
					 wG: "", // wG letter words
					 wH: "", // wH letter words
					 wI: "", // wI letter words
					 wJ: "", // wJ letter words
					 wK: "", // wK letter words
					 wL: "", // wL letter words
					 wM: "", // wM letter words
					 wN: "", // wN letter words
					 wO: "", // wO letter words
					 wP: "", // wP letter words
					 wQ: "", // wQ letter words
					 wR: "", // wR letter words
					 wS: "", // wS letter words
					 wT: "", // wT letter words
					 wU: "", // wU letter words
					 wV: "", // wV letter words
					 wW: "", // wW letter words
					 wX: "", // wX letter words
					 wY: "", // wY letter words
					 wZ: "", // wZ letter words
					 wa: "", // wa letter words
					 wb: "", // wb letter words
					 wc: "", // wc letter words
					 wd: "", // wd letter words
					 we: "", // we letter words
					 wf: "", // wf letter words
					 wg: "", // wg letter words
					 wh: "", // wh letter words
					 wi: "", // wi letter words
					 wj: "", // wj letter words
					 wk: "", // wk letter words
					 wl: "", // wl letter words
					 wm: "", // wm letter words
					 wn: "", // wn letter words
					 wo: "", // wo letter words
					 wp: "", // wp letter words
					 wq: "", // wq letter words
					 wr: "", // wr letter words
					 ws: "", // ws letter words
					 wt: "", // wt letter words
					 wu: "", // wu letter words
					 wv: "", // wv letter words
					 ww: "", // ww letter words
					 wx: "", // wx letter words
					 wy: "", // wy letter words
					 wz: "", // wz letter words
					 xA: "", // xA letter words
					 xB: "", // xB letter words
					 xC: "", // xC letter words
					 xD: "", // xD letter words
					 xE: "", // xE letter words
					 xF: "", // xF letter words
					 xG: "", // xG letter words
					 xH: "", // xH letter words
					 xI: "", // xI letter words
					 xJ: "", // xJ letter words
					 xK: "", // xK letter words
					 xL: "", // xL letter words
					 xM: "", // xM letter words
					 xN: "", // xN letter words
					 xO: "", // xO letter words
					 xP: "", // xP letter words
					 xQ: "", // xQ letter words
					 xR: "", // xR letter words
					 xS: "", // xS letter words
					 xT: "", // xT letter words
					 xU: "", // xU letter words
					 xV: "", // xV letter words
					 xW: "", // xW letter words
					 xX: "", // xX letter words
					 xY: "", // xY letter words
					 xZ: "", // xZ letter words
					 xa: "", // xa letter words
					 xb: "", // xb letter words
					 xc: "", // xc letter words
					 xd: "", // xd letter words
					 xe: "", // xe letter words
					 xf: "", // xf letter words
					 xg: "", // xg letter words
					 xh: "", // xh letter words
					 xi: "", // xi letter words
					 xj: "", // xj letter words
					 xk: "", // xk letter words
					 xl: "", // xl letter words
					 xm: "", // xm letter words
					 xn: "", // xn letter words
					 xo: "", // xo letter words
					 xp: "", // xp letter words
					 xq: "", // xq letter words
					 xr: "", // xr letter words
					 xs: "", // xs letter words
					 xt: "", // xt letter words
					 xu: "", // xu letter words
					 xv: "", // xv letter words
					 xw: "", // xw letter words
					 xx: "", // xx letter words
					 xy: "", // xy letter words
					 xz: "", // xz letter words
					 yA: "", // yA letter words
					 yB: "", // yB letter words
					 yC: "", // yC letter words
					 yD: "", // yD letter words
					 yE: "", // yE letter words
					 yF: "", // yF letter words
					 yG: "", // yG letter words
					 yH: "", // yH letter words
					 yI: "", // yI letter words
					 yJ: "", // yJ letter words
					 yK: "", // yK letter words
					 yL: "", // yL letter words
					 yM: "", // yM letter words
					 yN: "", // yN letter words
					 yO: "", // yO letter words
					 yP: "", // yP letter words
					 yQ: "", // yQ letter words
					 yR: "", // yR letter words
					 yS: "", // yS letter words
					 yT: "", // yT letter words
					 yU: "", // yU letter words
					 yV: "", // yV letter words
					 yW: "", // yW letter words
					 yX: "", // yX letter words
					 yY: "", // yY letter words
					 yZ: "", // yZ letter words
					 ya: "", // ya letter words
					 yb: "", // yb letter words
					 yc: "", // yc letter words
					 yd: "", // yd letter words
					 ye: "", // ye letter words
					 yf: "", // yf letter words
					 yg: "", // yg letter words
					 yh: "", // yh letter words
					 yi: "", // yi letter words
					 yj: "", // yj letter words
					 yk: "", // yk letter words
					 yl: "", // yl letter words
					 ym: "", // ym letter words
					 yn: "", // yn letter words
					 yo: "", // yo letter words
					 yp: "", // yp letter words
					 yq: "", // yq letter words
					 yr: "", // yr letter words
					 ys: "", // ys letter words
					 yt: "", // yt letter words
					 yu: "", // yu letter words
					 yv: "", // yv letter words
					 yw: "", // yw letter words
					 yx: "", // yx letter words
					 yy: "", // yy letter words
					 yz: "", // yz letter words
					 zA: "", // zA letter words
					 zB: "", // zB letter words
					 zC: "", // zC letter words
					 zD: "", // zD letter words
					 zE: "", // zE letter words
					 zF: "", // zF letter words
					 zG: "", // zG letter words
					 zH: "", // zH letter words
					 zI: "", // zI letter words
					 zJ: "", // zJ letter words
					 zK: "", // zK letter words
					 zL: "", // zL letter words
					 zM: "", // zM letter words
					 zN: "", // zN letter words
					 zO: "", // zO letter words
					 zP: "", // zP letter words
					 zQ: "", // zQ letter words
					 zR: "", // zR letter words
					 zS: "", // zS letter words
					 zT: "", // zT letter words
					 zU: "", // zU letter words
					 zV: "", // zV letter words
					 zW: "", // zW letter words
					 zX: "", // zX letter words
					 zY: "", // zY letter words
					 zZ: "", // zZ letter words
					 za: "", // za letter words
					 zb: "", // zb letter words
					 zc: "", // zc letter words
					 zd: "", // zd letter words
					 ze: "", // ze letter words
					 zf: "", // zf letter words
					 zg: "", // zg letter words
					 zh: "", // zh letter words
					 zi: "", // zi letter words
					 zj: "", // zj letter words
					 zk: "", // zk letter words
					 zl: "", // zl letter words
					 zm: "", // zm letter words
					 zn: "", // zn letter words
					 zo: "", // zo letter words
					 zp: "", // zp letter words
					 zq: "", // zq letter words
					 zr: "", // zr letter words
					 zs: "", // zs letter words
					 zt: "", // zt letter words
					 zu: "", // zu letter words
					 zv: "", // zv letter words
					 zw: "", // zw letter words
					 zx: "", // zx letter words
					 zy: "", // zy letter words
					 zz: ""  // zz letter words
			 };
			for(var i = 0; i < this.tmp.length;i++) {
				if(this.tmp[i].length == 1) {
					this.wArray[0]+=this.tmp[i] + "#";
				}
				else {
					this.wArray[this.tmp[i][0] + this.tmp[i][1]] += this.tmp[i] + "#";
				}
			}
			this.finish = true;
			console.log(this.wArray);

		});
	}

	// check if word is spelt right, if not a word atall (e.g. 12) it returns true
	isCorrect(word) {
		if(this.finish) {
			this.ret = false;
			if(word.length > 0) {
				if(word[word.length - 1] == '.' ||
					 word[word.length - 1] == '!' ||
				   word[word.length - 1] == '?') {
					word = word.substring(0,word.length - 1);
				}
				if(word.length == 1) {
					this.ret = this.wArray[0].includes(word+"#");
				}
				else {
					this.ret = this.wArray[word[0] + word[1]].includes(word+"#");
					if(this.ret == false) {
							word = word.toLowerCase();
							this.ret = this.wArray[word[0] + word[1]].includes(word +"#");
					}
				}
			}
			return this.ret;
		}
		return true;
	}

}
